version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:31112
functions:
  helloworld:
    lang: go
    handler: ./helloworld
    image: nachiket-p/helloworld:latest
  hello-python:
    lang: python3
    handler: ./hello-python
    image: nachiket-p/hello-python:latest
