version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:31112
functions:
  helloworld:
    lang: go
    handler: ./helloworld
    image: nachiketp/helloworld:latest
  hello-python:
    lang: python3
    handler: ./hello-python
    image: nachiketp/hello-python:latest
  to-csv:
    lang: node12
    handler: ./to-csv
    image: nachiketp/to-csv:latest
  fn-math:
    lang: fnkit-node12
    handler: ./fn-math
    image: fn-math:latest
